### ISSUE TITLE
gnome下用journalctl能看到qliveplayer的弹幕，不知能否让弹幕不被记录到log中

### ISSUE THREAD

**Issue by jian-lin** [THMonster/QLivePlayer#33]

**Comment by IsoaSFlus** [comment]
我下个版本改一下，让从非终端打开的直播不输出弹幕信息，这样应该就不会跑到systemd的日志里了

**Comment by ProbeC** [comment]
竟然看到你在github活跃呢，真是白让我担忧那么多年！

**Comment by IsoaSFlus** [comment]
> 竟然看到你在github活跃呢，真是白让我担忧那么多年！

你可以通过邮箱联系我，请不要滥用issue影响到其他人，我的邮箱me@isoasflus.com

**Comment by IsoaSFlus** [comment]
> 如果不是的话，那很抱歉打扰您，就不急需再乱留言啦。

我说了，无关事务请通过邮件联系，我的邮箱是 me@isoasflus.com。如果再abuse我就block你了。

**Comment by ProbeC** [comment]
***@***.***发邮件呀。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月7日(星期四) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IsoaSFlus/QLivePlayer] gnome下用journalctl能看到qliveplayer的弹幕，不知能否让弹幕不被记录到log中 (#33)





  
如果不是的话，那很抱歉打扰您，就不急需再乱留言啦。
  
我说了，无关事务请通过邮件联系，我的邮箱是 ***@***.***。如果再abuse我就block你了。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ProbeC** [comment]
***@***.***）总是退信。算了，我不打扰你了，可能是我认错人了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月7日(星期四) 晚上6:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IsoaSFlus/QLivePlayer] gnome下用journalctl能看到qliveplayer的弹幕，不知能否让弹幕不被记录到log中 (#33)





  
@.发邮件呀。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年10月7日(星期四) 下午5:46 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [IsoaSFlus/QLivePlayer] gnome下用journalctl能看到qliveplayer的弹幕，不知能否让弹幕不被记录到log中 (#33) 如果不是的话，那很抱歉打扰您，就不急需再乱留言啦。 我说了，无关事务请通过邮件联系，我的邮箱是 @.。如果再abuse我就block你了。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  

 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jian-lin** [comment]
确实，弹幕不被log了
